// Dave's monologue library (spec §14.3). Voice rule (§12): every line
// contains at least one quoted "they". Dave is genuinely good at his job.
// That is what makes this hard.
//
// v3: the real ones. These are actual conspiracies people hold, on the
// internet, with conviction — birds, Finland, the moon, the lizards —
// delivered by a man who can also definitely fix your press. The humor is
// in the commitment and the load-bearing tangents, not in the topic.

export const THEORIES = [
  "Birds aren't real, Spencer. Every pigeon on that chip pile is a surveillance drone — that's why they sit on the power lines, they're CHARGING. 'They' swapped the real ones out between '59 and '71. Follow the money. It ends at a binocular company. It always ends at a binocular company.",
  "Finland is not a real country. There's no landmass there — it's open ocean 'they' fenced off so Japan could overfish in private. Every 'Finn' you've met is eastern Sweden, paid to keep the bit going. Nokia was the hush money. I've never seen Finland. Neither have you. One of us is being honest about that.",
  "Australia's a cover story, Spencer. 'They' needed somewhere to say the convicts went, so a guy drew a continent and now there's a whole CGI budget for kangaroos. Every 'Australian' is an actor on a soundstage. They nailed the accent and got lazy on everything else. Look at a koala and tell me that renders.",
  "We never went to the moon. Kubrick shot it — 'they' had him do the deserts in '2001' as a screen test first. The flag WAVED, Spencer. There's no wind on the moon. There's no wind because there was no trip. This wrench has logged more vacuum than Neil Armstrong.",
  "Nobody's allowed to walk the edge of Antarctica. Ever wonder why? It's not a continent, it's the RIM. 'They' slapped a treaty on it in '59 and they patrol the ice wall so you don't go over the side. I'm not saying it's flat. I'm saying go measure it yourself and watch how fast 'they' show up.",
  "The board of directors are reptilian. Not a metaphor, Spencer. 'They' wear human suits and that's WHY corporate keeps it at sixty-eight degrees — reptiles need it cool or the suit stops sitting right. Watch the regional VP blink sideways one time. You'll never unsee it. I haven't slept since the Q2 review.",
  "The moon rings like a bell. Apollo dropped a spent stage on it and it rang for an HOUR — 'they' put that in the report and prayed nobody read it. It's hollow. It's a station. Same exact wobble as a load-bearing bearing somebody swapped for a counterfeit. I know that wobble. I'm hearing it right now, honestly.",
  "Contrails fade. Chemtrails don't — they fan out and the sky goes milky and that's the day the whole shift gets a headache. 'They' spray it. Ask yourself why the sunsets got so GOOD after 2010. Better sunsets, worse memory. That was the trade 'they' made on your behalf, no email, no opt-out.",
  "Denver International. Billions of dollars, middle of nowhere, four times bigger than it needs to be. There's a city UNDER it. 'They' put a demon horse out front with glowing red eyes — it killed the sculptor, that part's real, look it up — and the murals are about the apocalypse. It's an airport, Spencer. Why's the airport know about the apocalypse.",
  "It was the Berenstain Bears. You remember 'Berenstein.' EVERYBODY remembers Berenstein. 'They' didn't edit a children's book, Spencer — we slid one timeline over and the spelling rode along. The Monopoly man never had a monocle. You're positive he did. That's not your memory failing. That's the seam showing.",
  "It is not the year you think it is. 'They' inserted about three hundred years that never happened — the early Middle Ages, fabricated, Charlemagne's a composite. There's zero archaeology for entire centuries. By honest count it's roughly 1720. So this machine's warranty didn't expire, Spencer. It was never valid. Time fraud.",
  "Four mattress stores, one intersection, all empty, all open a decade. Nobody moves four hundred mattresses a month, but the rent clears every time. 'They' run money through them — you can't audit a thing nobody walks into. Same shape as this plant's 'consumables' line, if you ever feel like never sleeping on a paid-off mattress again.",
  "Paul McCartney died in '66. Car crash. 'They' ran a quiet lookalike contest and the winner's been 'Paul' ever since — that's why he's barefoot and out of step on the Abbey Road cover, that's how you bury a man in daylight. Play the records backward. I did. Couldn't prove it. Also can't sleep. Those might be related.",
  "When 'they' fired up that collider in Switzerland, something shifted — that's the exact week your memory of how things WERE stopped matching how things ARE. They opened a door and never shut it. Every glitch since is the draft coming through. This bearing dying tonight? Wrong timeline. In the right one it's fine. I miss the right one, Spencer.",
  "You ever personally dig up a dinosaur? No. 'They' show you a plaster cast in a lobby and call it a hundred million years old. Whole field was started by two rich men in a bone-buying feud in the 1800s — the Bone Wars, that's real — and it kept rolling because museums need a gift shop. This bearing's older than half their 'fossils,' and I can prove the bearing exists.",
];
